package com.example.newsapp.ui.theme

import androidx.compose.ui.graphics.Color

val PRIMARY_DARK = Color(0xffF64366)
val SECONDARY_DARK = Color(0xFF191369)
val SURFACE_DARK = Color(0xFF06051C)
val BACKGROUND_DARK = Color(0xff06051C)
val ON_PRIMARY_DARK = Color(0xffFFFFFF)
val ON_SECONDARY_DARK = Color(0xffFFFFFF)
val ON_SURFACE_DARK = Color(0xffFFFFFF)
val ON_SURFACE_VARIANT_DARK = Color(0xFFE9E8E8)
val ON_BACKGROUND_DARK = Color(0xffFFFFFF)
val OUTLINE_DARK = Color(0xFF979797)


val PRIMARY_LIGHT = Color(0xFF191369)
val SECONDARY_LIGHT = Color(0xffF64366)
val SURFACE_LIGHT = Color(0xffFFFFFF)
val BACKGROUND_LIGHT = Color(0xffFFFFFF)
val ON_PRIMARY_LIGHT = Color(0xffFFFFFF)
val ON_SECONDARY_LIGHT = Color(0xffFFFFFF)
val ON_SURFACE_LIGHT = Color(0xff06051C)
val ON_SURFACE_VARIANT_LIGHT = Color(0xFF242433)
val ON_BACKGROUND_LIGHT = Color(0xff06051C)
val OUTLINE_LIGHT = Color(0xFF979797)